import { type Meta, type StoryObj } from '@storybook/react-vite';
import DatePicker from '.';
declare const meta: Meta<typeof DatePicker>;
export default meta;
type Story = StoryObj<typeof DatePicker>;
export declare const Default: Story;
export declare const FormDatePickerDefault: Story;
export declare const FormDatePickerSmall: Story;
export declare const Disabled: Story;
export declare const DisableFuture: Story;
export declare const DisablePast: Story;
export declare const Timezone: Story;
export declare const ClearableField: Story;
export declare const Errors: Story;
export declare const DisabledDates: Story;
export declare const AllowedWeekendDays: Story;
export declare const FirstAvailableFromMonday: Story;
export declare const SlotPropsOverride: Story;
