import { type Meta, type StoryObj } from '@storybook/react-vite';
import CardContainer from '.';
declare const meta: Meta<typeof CardContainer>;
export default meta;
type Story = StoryObj<typeof CardContainer>;
export declare const Default: Story;
export declare const WithOnClick: Story;
export declare const WithOnClickNoAction: Story;
export declare const WithBadge: Story;
export declare const WithBadgeNoIcon: Story;
export declare const Error: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Info: Story;
export declare const Highlight: Story;
export declare const FullWidth: Story;
export declare const WithFooterSingleAction: Story;
export declare const WithFooterSingleActionAndNoHelper: Story;
export declare const WithFooterDoubleAction: Story;
export declare const WithBadgeAndFooter: Story;
export declare const EventPropagation: Story;
export declare const WithColorGrey: Story;
export declare const WithShadow: Story;
export declare const WithImg: Story;
