import { type Meta, type StoryObj } from '@storybook/react-vite';
import { type InputProps } from './types';
import InputClassic from '.';
declare const meta: Meta<typeof InputClassic>;
export default meta;
type Story = StoryObj<InputProps>;
export declare const NoLabel: Story;
export declare const DefaultWithHelper: Story;
export declare const InputSmall: Story;
export declare const Error: Story;
export declare const LongError: Story;
export declare const ErrorNoHelperText: Story;
export declare const Success: Story;
export declare const Disabled: Story;
export declare const WithBullet: Story;
export declare const WithLabelTooltip: Story;
export declare const FormInputClassicStory: Story;
export declare const FormInputClassicErrorStory: Story;
export declare const FormInputSmallStory: Story;
export declare const FormInputClassicMultilineStory: Story;
export declare const FormInputClassicWithStartAdorment: Story;
export declare const FormInputClassicWithStartAdormentMultiline: Story;
export declare const FormInputClassicWithMask: Story;
export declare const FormInputRename: Story;
