export const CURRENCIES = [
    { code: 'ARS', symbol: '$' },
    { code: 'BRL', symbol: 'R$' },
    { code: 'USD', symbol: '$' },
    { code: 'EUR', symbol: '€' },
    { code: 'GBP', symbol: '£' },
    { code: 'AUD', symbol: '$' },
    { code: 'BGN', symbol: 'лв' },
    { code: 'BOB', symbol: 'Bs.' },
    { code: 'CAD', symbol: '$' },
    { code: 'CLP', symbol: '$' },
    { code: 'COP', symbol: '$' },
    { code: 'CRC', symbol: '₡' },
    { code: 'DKK', symbol: 'kr' },
    { code: 'DOP', symbol: 'RD$' },
    { code: 'GTQ', symbol: 'Q' },
    { code: 'HNL', symbol: 'L' },
    { code: 'HUF', symbol: 'Ft' },
    { code: 'INR', symbol: '₹' },
    { code: 'ISK', symbol: 'kr' },
    { code: 'JPY', symbol: '¥' },
    { code: 'MXN', symbol: '$' },
    { code: 'MYR', symbol: 'RM' },
    { code: 'NOK', symbol: 'kr' },
    { code: 'NPR', symbol: 'Rs' },
    { code: 'NZD', symbol: '$' },
    { code: 'PEN', symbol: 'S/' },
    { code: 'PHP', symbol: '₱' },
    { code: 'PLN', symbol: 'zł' },
    { code: 'PYG', symbol: '₲' },
    { code: 'RON', symbol: 'lei' },
    { code: 'RSD', symbol: 'дин.' },
    { code: 'SEK', symbol: 'kr' },
    { code: 'SGD', symbol: '$' },
    { code: 'SZL', symbol: 'E' },
    { code: 'THB', symbol: '฿' },
    { code: 'TRY', symbol: '₺' },
    { code: 'UAH', symbol: '₴' },
    { code: 'UYU', symbol: '$U' },
    { code: 'VES', symbol: 'Bs.' },
];
export const currencyOptions = {
    de: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
    'en-US': {
        fractionSeparator: '.',
        groupingSeparator: ',',
    },
    'en-GB': {
        fractionSeparator: '.',
        groupingSeparator: ',',
    },
    es: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
    pt: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
    bg: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
    fr: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
    nb: {
        fractionSeparator: ',',
        groupingSeparator: '.',
    },
};
