import { type Meta, type StoryObj } from '@storybook/react-vite';
import DatePickerWithOptions from '.';
declare const meta: Meta<typeof DatePickerWithOptions>;
export default meta;
type Story = StoryObj<typeof DatePickerWithOptions>;
export declare const Default: Story;
export declare const OnlyDatePickers: Story;
export declare const OnlyOptions: Story;
export declare const SingleDatePicker: Story;
export declare const CustomCardStyling: Story;
export declare const WithoutCardContainer: Story;
export declare const CustomSpacing: Story;
export declare const WithRadioDescriptions: Story;
export declare const WithLabel: Story;
