import { type Meta, type StoryObj } from '@storybook/react-vite';
import Avatar from '.';
declare const meta: Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof Avatar>;
export declare const Default: Story;
export declare const FallbackText: Story;
export declare const FallbackAlt: Story;
export declare const Fallback: Story;
export declare const IconSmall: Story;
export declare const IconMedium: Story;
export declare const IconLarge: Story;
export declare const SquareAvatar: Story;
export declare const Loading: Story;
export declare const LoadingSmall: Story;
export declare const LoadingLarge: Story;
export declare const LoadingRounded: Story;
export declare const LoadingSquare: Story;
export declare const Badge: Story;
export declare const BadgeNumber: Story;
export declare const BadgeMax: Story;
