import { type Meta, type StoryObj } from '@storybook/react-vite';
import FormTimePicker from './form';
import TimePicker from './index';
declare const meta: Meta<typeof TimePicker>;
export default meta;
type Story = StoryObj<typeof TimePicker>;
export declare const Default: Story;
export declare const Timezone: Story;
export declare const WithValue: Story;
export declare const Small: Story;
export declare const Disabled: Story;
export declare const Error: Story;
export declare const FullWidth: Story;
export declare const MinutesStep5: Story;
export declare const NoIcon: Story;
type FormStory = StoryObj<typeof FormTimePicker>;
export declare const FormTimePickerDefault: FormStory;
export declare const FormTimePickerWithReferenceDate: FormStory;
export declare const FormTimePickerError: FormStory;
