import { type Meta, type StoryObj } from '@storybook/react-vite';
import FormInputTime from './form';
import InputTime from '.';
declare const meta: Meta<typeof InputTime>;
export default meta;
type Story = StoryObj<typeof InputTime>;
export declare const Default: Story;
export declare const WithValue: Story;
export declare const Small: Story;
export declare const Disabled: Story;
export declare const WithError: Story;
export declare const FullWidth: Story;
export declare const MinutesStep1: Story;
export declare const NoIcon: Story;
export declare const WithAmPm: Story;
export declare const WithAmPmAndValue: Story;
type FormStory = StoryObj<typeof FormInputTime>;
export declare const FormDefault: FormStory;
export declare const FormWithReferenceDate: FormStory;
export declare const FormError: FormStory;
