import { type Meta, type StoryObj } from '@storybook/react-vite';
declare const meta: Meta;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Disabled: Story;
export declare const Loading: Story;
export declare const CollaboratorsReachEmpty: Story;
export declare const CollaboratorsReachLoading: Story;
export declare const CollaboratorsReachReady: Story;
