import { type Meta, type StoryObj } from '@storybook/react-vite';
import { type AutocompleteOption, type AutocompleteProps } from './types';
type MockOption = {
    value: number;
    label: string;
};
declare const meta: Meta<AutocompleteProps<MockOption>>;
export default meta;
type Story = StoryObj<AutocompleteProps<MockOption>>;
export declare const Default: Story;
export declare const Error: Story;
export declare const NoOptions: Story;
export declare const HelperText: Story;
export declare const WithInputType: Story;
export declare const Disabled: Story;
export declare const Loading: Story;
export declare const multiple: StoryObj<AutocompleteProps<MockOption, true>>;
export declare const NoTags: StoryObj<AutocompleteProps<MockOption, true>>;
export declare const ServerFiltered: Story;
export declare const Creatable: Story;
export declare const MultipleCreatable: StoryObj<AutocompleteProps<MockOption, true>>;
export declare const LoadMore: Story;
export declare const CreatableLoadMore: Story;
export declare const Form: Story;
export declare const FormDisabled: Story;
export declare const FormLimitedTagsDisabled: Story;
export declare const StressTest15K: Story;
export declare const StressTest15KMultiple: StoryObj<AutocompleteProps<AutocompleteOption, true>>;
export declare const StressTest15KNoVirtualization: Story;
