import { type Meta, type StoryObj } from '@storybook/react-vite';
import UserCard from '.';
declare const meta: Meta<typeof UserCard>;
export default meta;
type Story = StoryObj<typeof UserCard>;
export declare const Default: Story;
export declare const SingleButton: Story;
export declare const TwoButtons: Story;
export declare const ThreeButtons: Story;
export declare const ThreeButtonsWithIcons: Story;
export declare const ButtonVariants: Story;
export declare const MixedButtonVariants: Story;
export declare const WithProfilePicture: Story;
export declare const LongTextOverflow: Story;
export declare const CustomWidth: Story;
export declare const ThreeButtonsInDifferentWidths: Story;
export declare const CustomLabels: Story;
export declare const CustomHeaderColor: Story;
export declare const WithoutActionButtons: Story;
export declare const WithoutCopyButton: Story;
export declare const WithoutEmail: Story;
export declare const DifferentAvatarSizes: Story;
export declare const InteractiveDemo: Story;
export declare const WithExtendedUserType: Story;
export declare const LoadingButtons: Story;
export declare const DisabledButtons: Story;
